### Config file for CRISPRiTilingDesign pipeline

## Definitions:
##  Region aka guideSet - a (usually) small genomic range among which gRNAs are chosen, e.g. DNase peak or promoter
##  RegionGroup - name for an arbitrary group of regions (e.g., all DNase peaks near a given gene)
##  Pool - a set of oligos for pooled synthesis
##  Subpool - a subset of a pool of oligos, usually with unique primer sites to enable PCR amplifying out the subpool


## Genome files
##   Download off_target_bits files for hg19 or mm9 from https://drive.google.com/drive/u/1/folders/1F5-v0KopsE7hshjwMbHEryXd2wkDdR2Q
project_root: "/mnt/c/Users/chano/Bioinformatics/251028_gRNA_design/CRISPRDesigner"
genome_fasta: "data/hg19.fa"
genome_sizes: "data/hg19.chrom.sizes"
off_target_bits: "data/hg19.CRISPR.bit"
promoters: "data/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS500bp.bed"

## 
regions: "data/enhancer_information_Timoriginal_extracted.bed"

## Pre-designed gRNAs (provide so designer will not redesign or rescore guides in these regions, to save compute time)
#predesigned_guides: {
  #Prior210615: {  ## These files can be downloaded from https://drive.google.com/drive/u/1/folders/1F5-v0KopsE7hshjwMbHEryXd2wkDdR2Q
    #guides: "/oak/stanford/groups/engreitz/Projects/CRISPRDesign/210615_CollatedFilteredGuides/filteredGuides.210615Combined.bed",
    #regions: "/oak/stanford/groups/engreitz/Projects/CRISPRDesign/210615_CollatedFilteredGuides/regions.210615Combined.bed"
 # }
#}

java_memory:      "16g"  ## Increase if Java command fails (sometimes needs up to 64g for large sets of regions) 
split_guides:     50    ## Split scoring into chunks of N guideRNAs


